name: docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t doctr-tf-py3.8-slim
      - name: Run docker container
        run: docker run doctr-tf-py3.8-slim python -c 'import doctr'

  pytest-api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Lock the requirements
        run: |
          cd api
          make lock
      - name: Build & run docker
        run: cd api && docker-compose up -d --build
      - name: Ping server
        run: wget --spider --tries=12 http://localhost:8080/docs
      - name: Run docker test
        run: |
          docker cp api/requirements-dev.txt api_web_1:/app/requirements-dev.txt
          docker-compose -f api/docker-compose.yml exec -T web pip install -r requirements-dev.txt
          docker cp api/tests api_web_1:/app/tests
          docker-compose -f api/docker-compose.yml exec -T web pytest tests/
